# Generated by Django 5.2.3 on 2025-07-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(verbose_name='model name')),
                ('instructions', models.TextField(default='\n        <ul>\n            <li>Charge the device with the included charger and cable</li>\n            <li>Power on this device by pressing the button on the front panel.</li>  \n            <li>Connect your device to this device using the SSID and password printed in this documentation</li>\n        </ul>\n        ')),
                ('instructions_photo', models.ImageField(upload_to='hotspot_insert_generator', verbose_name='photo for instructions')),
            ],
        ),
    ]
