# Generated by Django 5.2.3 on 2025-07-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_insert_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='instructions_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotspot_insert_generator', verbose_name='photo for instructions'),
        ),
    ]
