# Generated by Django 5.2.7 on 2026-01-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_insert_generator', '0002_alter_devicemodel_instructions_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_title', models.CharField(verbose_name='template title')),
                ('template_filename', models.CharField(verbose_name='template file name')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceModel',
        ),
    ]
