# Generated by Django 5.2.7 on 2026-01-24 20:11

from django.db import migrations

def add_templates(apps, schema_editor):
    InsertTemplate = apps.get_model("hotspot_insert_generator", "InsertTemplate")
    InsertTemplate.objects.get_or_create(
        template_filename="insert_orbic4400l_ace320070.html",
        defaults={
            "template_title": "OrbicR4400l_Ace320070"
        }
    )
    InsertTemplate.objects.get_or_create(
        template_filename="insert_orbic4400l_pelican1050.html",
        defaults={
            "template_title": "OrbicR4400l_Pelican1050"
        }

    )


class Migration(migrations.Migration):
    dependencies = [
        ('hotspot_insert_generator', '0003_inserttemplate_delete_devicemodel'),
    ]

    operations = [
        migrations.RunPython(add_templates)
    ]
