# Generated by Django 6.0.3 on 2026-05-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_insert_generator', '0004_auto_20260124_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='inserttemplate',
            name='stylesheet_filename',
            field=models.CharField(blank=True, help_text='The name of the stylesheet file', max_length=50, verbose_name='stylesheet file name'),
        ),
        migrations.AlterField(
            model_name='inserttemplate',
            name='template_filename',
            field=models.CharField(blank=True, help_text='The name of the template file', max_length=50, verbose_name='template file name'),
        ),
        migrations.AlterField(
            model_name='inserttemplate',
            name='template_title',
            field=models.CharField(blank=True, help_text='The title of this template', max_length=50, verbose_name='template title'),
        ),
    ]
